#!/usr/bin/env python3
from __future__ import annotations

"""
Phase 0 – AI test selection script.

Given a git diff (via --base/--head or --diff-file), calls Azure OpenAI to select
which Playwright E2E tests (discovered via glob under Worklist-2/playwright) should run.
Outputs selected paths and the npx playwright test ... command.

Usage (from E2E-Affected-Tests-POC or scripts/):
  python select_tests.py --repo ../OmegaAI-Mono --base master --head HEAD
  python select_tests.py --diff-file path/to/diff.txt [--approach summaries|full]
  python select_tests.py --repo ... --base master --head HEAD --two-stage

Behavior:
  - Successful API + empty or unparseable model reply → no tests selected.
  - API / transport failure → fall back to all discovered spec files (safe default).
  - last_model_response.txt = final selected paths (one per line, or "(none)"); last_model_raw_response.txt
    = raw assistant text (Stage 2 in --two-stage, full reply in single-shot).
  - --two-stage: Stage 1 = wide-net candidates; Stage 2 = final pick (precision default, --stage2-balanced,
    or --stage2-recall). last_stage2_merged_paths.txt = merge-only paths.
"""

import argparse
import os
import re
import subprocess
import sys
import time
from pathlib import Path


def log_step(step: str, detail: str = "") -> None:
    """Print a numbered pipeline step to stderr for debugging (where failures occur)."""
    if detail:
        print(f"[select_tests] STEP: {step} — {detail}", file=sys.stderr)
    else:
        print(f"[select_tests] STEP: {step}", file=sys.stderr)


def _log_azure_api_exception(label: str, e: BaseException) -> None:
    """Print exception type, message, HTTP status/body when available (OpenAI/Azure errors)."""
    print(f"[select_tests] STEP ERROR [{label}]: type={type(e).__name__}", file=sys.stderr)
    print(f"[select_tests] STEP ERROR [{label}]: {e!r}", file=sys.stderr)
    sc = getattr(e, "status_code", None)
    if sc is not None:
        print(f"[select_tests] STEP ERROR [{label}]: HTTP status_code={sc}", file=sys.stderr)
    body = getattr(e, "body", None)
    if body is not None:
        body_s = repr(body)
        if len(body_s) > 4000:
            body_s = body_s[:4000] + "..."
        print(f"[select_tests] STEP ERROR [{label}]: body={body_s}", file=sys.stderr)
    resp = getattr(e, "response", None)
    if resp is not None and body is None:
        txt = getattr(resp, "text", None)
        if txt:
            t = txt if len(txt) <= 4000 else txt[:4000] + "..."
            print(f"[select_tests] STEP ERROR [{label}]: response.text={t!r}", file=sys.stderr)
    err_obj = getattr(e, "error", None)
    if err_obj is not None:
        print(f"[select_tests] STEP ERROR [{label}]: nested error={err_obj!r}", file=sys.stderr)
    cause = e.__cause__
    if cause is not None:
        print(f"[select_tests] STEP ERROR [{label}]: __cause__={cause!r}", file=sys.stderr)

# Load .env from script directory so API key etc. are available without setting env each time
try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent / ".env")
except ImportError:
    pass  # python-dotenv not installed; use env vars only

# ---------------------------------------------------------------------------
# Checkpoint 3: Discover Playwright specs (paths relative to playwright/)
# Glob: Worklist-2/playwright/**/*.spec.js — sorted for stable order.
# Summaries are loaded from test_summaries.json (generated by generate_summaries.py).
# Optional snapshot: ../playwright_spec_paths.txt (documentation only; not read by scripts).
# ---------------------------------------------------------------------------
def playwright_dir(repo_path: Path) -> Path:
    """Absolute path to Worklist-2/playwright for a mono repo root."""
    return repo_path / "Worklist-2" / "playwright"


def discover_playwright_spec_paths(repo_path: Path) -> list[str]:
    """
    Return all *.spec.js paths under Worklist-2/playwright, relative to that folder,
    using forward slashes, sorted lexicographically.
    """
    root = playwright_dir(repo_path)
    if not root.is_dir():
        return []
    out: list[str] = []
    for p in sorted(root.rglob("*.spec.js")):
        rel = p.relative_to(root)
        out.append(str(rel).replace("\\", "/"))
    return out


def _summaries_json_path() -> Path:
    """Path to test_summaries.json (next to this script)."""
    return Path(__file__).resolve().parent / "test_summaries.json"


def get_test_summaries(repo_path: Path) -> list[tuple[str, str]]:
    """
    Return list of (path, one_line_summary) for Approach A.
    Loads from test_summaries.json; use generate_summaries.py to create/update it.
    Missing file or missing key -> "No summary".
    """
    import json
    paths = discover_playwright_spec_paths(repo_path)
    json_path = _summaries_json_path()
    if not json_path.exists():
        print("Note: test_summaries.json not found. Run generate_summaries.py first.", file=sys.stderr)
        return [(path, "No summary") for path in paths]
    try:
        data = json.loads(json_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        print(f"Warning: could not load {json_path}: {e}", file=sys.stderr)
        return [(path, "No summary") for path in paths]
    return [(path, data.get(path, "No summary")) for path in paths]


def get_test_full_contents(repo_path: Path) -> list[tuple[str, str]]:
    """Return list of (path, full_file_content) for Approach B. Skips missing files with a warning."""
    results = []
    pw_dir = playwright_dir(repo_path)
    for path in discover_playwright_spec_paths(repo_path):
        full_path = pw_dir / path
        if not full_path.exists():
            print(f"Warning: test file not found: {full_path}", file=sys.stderr)
            continue
        try:
            content = full_path.read_text(encoding="utf-8", errors="replace")
            results.append((path, content))
        except OSError as e:
            print(f"Warning: could not read {full_path}: {e}", file=sys.stderr)
    return results


def get_available_tests(repo_path: Path, approach: str) -> list[tuple[str, str]]:
    """
    Return list of (path, text) for all discovered *.spec.js tests.
    - approach "summaries": text = one-line summary from test_summaries.json.
    - approach "full": text = full spec file content (read from repo_path/Worklist-2/playwright/).
    """
    if approach == "summaries":
        return get_test_summaries(repo_path)
    if approach == "full":
        return get_test_full_contents(repo_path)
    raise ValueError(f"Unknown approach: {approach}")


def resolve_repo_path(repo_arg: str) -> Path:
    """Resolve repo path to absolute. Relative paths are relative to cwd."""
    p = Path(repo_arg)
    if not p.is_absolute():
        p = Path.cwd() / p
    return p.resolve()


def run_git(repo_path: Path, *args: str) -> str:
    """Run git in repo_path with given args. Returns stdout. Raises on non-zero exit."""
    cmd = ["git", *args]
    result = subprocess.run(
        cmd,
        cwd=repo_path,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {result.stderr or result.stdout}")
    return result.stdout


def parse_diff_git_paths(diff_text: str) -> list[str]:
    """Extract changed file paths from 'diff --git a/path b/path' lines."""
    paths = []
    for m in re.finditer(r"^diff --git a/(.+?) b/.+", diff_text, re.MULTILINE):
        path = m.group(1).strip()
        if path and path not in paths:
            paths.append(path)
    return paths


# ---------------------------------------------------------------------------
# Checkpoint 4: Prompt building (system + user messages for the AI)
# ---------------------------------------------------------------------------
MAX_DIFF_CHARS = 12_000  # Truncate diff to avoid token limits
# Stage 2: per-spec truncation (same order of magnitude as generate_summaries.py's 8000)
STAGE2_SPEC_MAX_CHARS = 10_000
# Stage 2: cap total snippet size across all Stage-1 candidates. Without this, many candidates × 10k
# chars explodes the prompt (~60k+ tokens) and models like gpt-5-mini often return empty message.content.
STAGE2_TOTAL_SNIPPET_BUDGET_CHARS_DEFAULT = 100_000
STAGE2_PER_SPEC_FLOOR_CHARS = 200  # minimum per spec when budget is tight (still truncated)


def _default_max_completion_tokens() -> int:
    return int(os.environ.get("AZURE_OPENAI_SELECTION_MAX_COMPLETION_TOKENS", "8192"))


def _stage1_max_completion_tokens() -> int:
    return int(os.environ.get("AZURE_OPENAI_STAGE1_MAX_COMPLETION_TOKENS", "16384"))


def _stage2_max_completion_tokens() -> int:
    # Reasoning models charge reasoning_tokens inside completion_tokens; default must leave room
    # for paths after reasoning (see completion_tokens_details in logs).
    return int(os.environ.get("AZURE_OPENAI_STAGE2_MAX_COMPLETION_TOKENS", "16384"))


def _stage2_total_snippet_budget_chars() -> int:
    return int(
        os.environ.get(
            "STAGE2_MAX_TOTAL_SNIPPET_CHARS",
            str(STAGE2_TOTAL_SNIPPET_BUDGET_CHARS_DEFAULT),
        )
    )


def stage2_per_spec_max_chars(num_candidates: int) -> int:
    """
    Per-spec char cap for Stage 2 so total snippets stay within STAGE2_MAX_TOTAL_SNIPPET_CHARS.
    When Stage 1 returns many paths, each spec gets less than STAGE2_SPEC_MAX_CHARS automatically.
    """
    if num_candidates <= 0:
        return STAGE2_SPEC_MAX_CHARS
    budget = _stage2_total_snippet_budget_chars()
    per = budget // num_candidates
    per = max(STAGE2_PER_SPEC_FLOOR_CHARS, per)
    return min(STAGE2_SPEC_MAX_CHARS, per)


def build_prompt(
    changed_files: list[str],
    full_diff: str | None,
    available_tests: list[tuple[str, str]],
) -> tuple[str, str]:
    """
    Build system and user messages for the test-selection AI.
    Returns (system_message, user_message).
    """
    system_message = (
        "You are a test-selection assistant. You are given a code change (changed files and optionally a diff) "
        "and a list of **Available tests** (each entry: path + short description of what that E2E test covers). "
        "Your job is to pick which of those tests should run for this change.\n\n"
        "Rules (same whether there are few or many tests):\n"
        "1. **Minimum set**: Include only tests you can justify from the changed paths and diff. Do not add tests "
        "\"to be safe,\" for broad product familiarity, or because areas feel loosely related.\n"
        "2. **Evidence**: For every path you output, there must be a clear link between the change and that test's "
        "description in the Available tests list (file paths, feature names, UI strings, or behavior visible in the diff).\n"
        "3. **Shared components**: Changes to shared UI (tables, grids, layout, generic components) may affect many "
        "features. Select a test only if **that test's description** matches what this change plausibly affects. "
        "Do **not** select tests for unrelated feature areas just because they also use a shared component elsewhere "
        "in the app.\n"
        "4. **Use the list**: The Available tests section is the source of truth for paths and scope. Rely on each "
        "line's description to decide fit; do not invent paths.\n\n"
        "Output format: reply with **only** the test file paths from the Available tests list, **one path per line**, "
        "using the **exact** path strings shown. No explanations, bullets, markdown, or other text. "
        "If no listed test is justified, reply with **no lines** (empty response)."
    )

    parts = ["Changed files:"]
    for p in changed_files:
        parts.append(f"  {p}")
    parts.append("")

    if full_diff and full_diff.strip():
        diff_text = full_diff.strip()
        if len(diff_text) > MAX_DIFF_CHARS:
            diff_text = diff_text[:MAX_DIFF_CHARS] + "\n\n... (diff truncated)"
            parts.append("Diff (truncated):")
        else:
            parts.append("Diff:")
        parts.append(diff_text)
        parts.append("")
    else:
        parts.append("Diff: (none)")
        parts.append("")

    parts.append("Available tests:")
    for path, text in available_tests:
        # Use path exactly as returned by discover_playwright_spec_paths for consistent parsing
        if len(text) > 500:
            parts.append(f"  {path}:")
            parts.append(text[:500] + "\n... (content truncated)")
        else:
            parts.append(f"  {path} — {text}")
    parts.append("")
    parts.append(
        "Which of the above tests are **directly** justified by this change? Reply with only those paths, "
        "one per line, no other text. Prefer the smallest sufficient set; use each test's description to "
        "match scope to the change. If none apply, reply with nothing."
    )

    user_message = "\n".join(parts)
    return system_message, user_message


def build_stage1_candidate_prompt(
    changed_files: list[str],
    full_diff: str | None,
    available_tests: list[tuple[str, str]],
) -> tuple[str, str]:
    """
    Stage 1 — recall-focused candidate list from paths + summaries only.
    Model chooses how many paths to include (no fixed cap); cast a wide net.
    """
    system_message = (
        "You are a **candidate-generation** assistant for E2E test selection.\n\n"
        "You are given a code change (changed files and optionally a diff) and **Available tests**: "
        "each line is a Playwright spec path plus a short summary of what that test covers.\n\n"
        "**Goal — recall first:** List **every** spec from Available tests that could **plausibly** be "
        "relevant to this change — including **borderline**, **indirect**, or **remotely connected** cases. "
        "Cast a **wide net**. Prefer **including** a spec when unsure rather than omitting it. "
        "This stage is **not** for finding the smallest set.\n\n"
        "Rules:\n"
        "- Output **only** paths that appear in the Available tests list, using the **exact** path strings.\n"
        "- **One path per line.** No explanations, bullets, markdown, numbering, or extra text.\n"
        "- Include **as many** plausible candidates as needed; **do not** limit yourself to a small number "
        "for brevity.\n"
        "- Do **not** invent paths.\n"
        "- If **nothing** in the list is even remotely related, reply with **no lines** (empty response)."
    )

    parts = ["Changed files:"]
    for p in changed_files:
        parts.append(f"  {p}")
    parts.append("")

    if full_diff and full_diff.strip():
        diff_text = full_diff.strip()
        if len(diff_text) > MAX_DIFF_CHARS:
            diff_text = diff_text[:MAX_DIFF_CHARS] + "\n\n... (diff truncated)"
            parts.append("Diff (truncated):")
        else:
            parts.append("Diff:")
        parts.append(diff_text)
        parts.append("")
    else:
        parts.append("Diff: (none)")
        parts.append("")

    parts.append("Available tests:")
    for path, text in available_tests:
        if len(text) > 500:
            parts.append(f"  {path}:")
            parts.append(text[:500] + "\n... (content truncated)")
        else:
            parts.append(f"  {path} — {text}")
    parts.append("")
    parts.append(
        "Reply with **only** the candidate test paths (wide net, recall-first), one per line, "
        "exact paths from the list above."
    )

    return system_message, "\n".join(parts)


def get_truncated_spec_snippets(
    repo_path: Path,
    paths: list[str],
    max_chars: int = STAGE2_SPEC_MAX_CHARS,
) -> list[tuple[str, str]]:
    """
    For each path, read spec under Worklist-2/playwright/<path> and truncate to max_chars.
    Skips missing files with a warning; order matches `paths`.
    """
    pw_dir = playwright_dir(repo_path)
    out: list[tuple[str, str]] = []
    for path in paths:
        full_path = pw_dir / path
        if not full_path.exists():
            print(f"Warning: test file not found for Stage 2: {full_path}", file=sys.stderr)
            continue
        try:
            content = full_path.read_text(encoding="utf-8", errors="replace")
        except OSError as e:
            print(f"Warning: could not read {full_path}: {e}", file=sys.stderr)
            continue
        if len(content) > max_chars:
            snippet = content[:max_chars] + "\n\n... (spec truncated)"
        else:
            snippet = content
        out.append((path, snippet))
    return out


def build_stage2_final_prompt(
    changed_files: list[str],
    full_diff: str | None,
    path_and_snippets: list[tuple[str, str]],
    *,
    stage2_mode: str = "precision",
) -> tuple[str, str]:
    """
    Stage 2 — final selection using changed files, diff, and truncated spec bodies for Stage-1 candidates only.

    stage2_mode:
      - ``precision`` — smallest necessary set (default).
      - ``balanced`` — slightly wider: 2–5 paths when several distinct flows plausibly apply.
      - ``recall`` — recall-first; keep every plausible candidate (legacy).
    """
    if stage2_mode == "recall":
        system_message = (
            "You are a **final test-selection** assistant for Playwright E2E tests.\n\n"
            "You are given the code change and **truncated contents** of candidate spec files (Stage 1 already "
            "narrowed the universe). Your job is to output the tests that should run for this change.\n\n"
            "**Recall first — do not minimize:** Include **every** spec whose path appears below if that test "
            "could **plausibly fail** or **needs validation** for this change. Do **not** omit a necessary test "
            "to shorten the list. **Extra** specs are acceptable when in doubt.\n\n"
            "Output **only** paths from the candidate set provided below (the paths shown before each snippet), "
            "using the **exact** path strings. **One path per line.** No explanations, bullets, markdown, or other text. "
            "If none of the candidates apply, reply with **no lines** (empty response)."
        )
        closing = (
            "Reply with **only** the paths to run, one per line (exact paths from the --- headers above). "
            "Recall-first: include every candidate that could plausibly need to run for this change."
        )
    elif stage2_mode == "balanced":
        system_message = (
            "You are a **final test-selection** assistant for Playwright E2E tests.\n\n"
            "You are given the code change and **truncated contents** of candidate spec files (Stage 1 already "
            "produced a broad list). Your job is to output a **small** set of tests — **slightly wider** than the "
            "bare minimum: allow **light** over-inclusion when several Stage-1 candidates cover **different** user "
            "flows or surfaces for the same product area.\n\n"
            "**Balanced — modest recall (not full Stage 1 list):**\n"
            "- Still **omit** candidates that are clearly unrelated to the diff.\n"
            "- If **multiple** Stage-1 paths sit under the **same product line** (e.g. shared prefix like `Blume/` "
            "or neighboring folders such as `BlumeHome/`, `BlumeForms/`, `BlumeDocuments/`) and the change is "
            "**non-trivial** (several changed files, assets, strings, or cross-cutting behavior), prefer **2–5** "
            "paths that each plausibly exercise a **distinct** flow — do **not** collapse to a single spec by default "
            "in that situation.\n"
            "- If **roughly five or more** files appear under Changed files, include **at least two** paths when "
            "at least two candidates each have a plausible link to the change.\n"
            "- When the diff clearly touches **only one** narrow behavior, **one** path is enough.\n"
            "- Do **not** output the entire Stage 1 candidate list unless most lines are genuinely justified.\n\n"
            "Output **only** paths from the candidate set below (paths before each `---` block), using the **exact** "
            "path strings. **One path per line.** No explanations, bullets, markdown, or other text. "
            "If none of the candidates are justified, reply with **no lines** (empty response)."
        )
        closing = (
            "Reply with **only** the paths to run, one per line (exact paths from the --- headers above). "
            "Balanced: a **small** set with **light** over-inclusion when several distinct flows apply."
        )
    else:
        system_message = (
            "You are a **final test-selection** assistant for Playwright E2E tests.\n\n"
            "You are given the code change and **truncated contents** of candidate spec files (Stage 1 already "
            "produced a broad candidate list). Your job is to output the **smallest sufficient** set of tests "
            "that should run for **this specific change**.\n\n"
            "**Precision — minimize false positives:**\n"
            "- Include a path **only** if this diff could plausibly cause that test to **fail**, or require "
            "an update, because of what the test **asserts or exercises** (selectors, visible text, tool names, "
            "feature behavior tied to the changed code).\n"
            "- Do **not** include tests merely because they belong to the same broad area (e.g. generic toolbar, "
            "viewer, or navigation) if the diff does **not** plausibly affect what those tests check.\n"
            "- For **small or localized** changes (e.g. a label, string, or single control), prefer **few** specs — "
            "often **one** — that directly cover that surface; do not add \"related\" specs for safety.\n"
            "- Include **more** paths only when the diff clearly spans multiple features, files, or behaviors.\n"
            "- **Specificity over breadth:** If Stage 1 listed a candidate whose **filename** clearly names the "
            "feature or control in the **changed file path** (e.g. `windowLevelTool.spec.js` for a change under "
            "`.../Wheel/tools.js` affecting window/level wording), **prefer that spec** over broader tests "
            "(generic toolbar, another wheel control, or \"nearby\" viewer tests) unless the diff clearly touches those.\n"
            "- **Do not drop** the most **specific** Stage-1 candidate that directly names the changed behavior "
            "in favor of a looser test that only partially overlaps.\n"
            "- **Multiple changed files:** If **two or more** different files appear under Changed files above, do **not** "
            "collapse the whole diff to a **single** test when distinct areas are affected (e.g. organization user "
            "copy vs shared DataGrid). Include **at least one** justified path per **changed file** (or per clearly "
            "distinct feature), unless an extra file is only a trivial rename with no test impact.\n"
            "- **DataGrid / `data-cy` / worklist table:** If the diff changes **`data-cy`**, **`Table`**, or **`DataGrid`** "
            "in worklist UI, prefer specs that cover **table behavior, row selection, or the study grid** — not only "
            "a loosely related \"worklist\" test with a similar name.\n"
            "- **Naming:** **WorklistSelection** (row selection, multi-select) vs **WorklistSelector** (which worklist / "
            "layout) are different features; pick the candidate whose **path and summary** match **what** the diff "
            "touches (table vs picker), not just the word \"worklist\".\n\n"
            "Output **only** paths from the candidate set below (paths before each `---` block), using the **exact** "
            "path strings. **One path per line.** No explanations, bullets, markdown, or other text. "
            "If none of the candidates are justified by this diff, reply with **no lines** (empty response)."
        )
        closing = (
            "Reply with **only** the paths to run, one per line (exact paths from the --- headers above). "
            "Smallest sufficient set for **this** diff — do not pad the list."
        )

    parts = ["Changed files:"]
    for p in changed_files:
        parts.append(f"  {p}")
    parts.append("")

    if full_diff and full_diff.strip():
        diff_text = full_diff.strip()
        if len(diff_text) > MAX_DIFF_CHARS:
            diff_text = diff_text[:MAX_DIFF_CHARS] + "\n\n... (diff truncated)"
            parts.append("Diff (truncated):")
        else:
            parts.append("Diff:")
        parts.append(diff_text)
        parts.append("")
    else:
        parts.append("Diff: (none)")
        parts.append("")

    parts.append("Candidate specs (path + truncated file content; paths are the only valid outputs):")
    for path, snippet in path_and_snippets:
        parts.append("")
        parts.append(f"--- {path} ---")
        parts.append(snippet)
    parts.append("")
    parts.append(closing)

    return system_message, "\n".join(parts)


# ---------------------------------------------------------------------------
# Checkpoint 5: Azure OpenAI call for test selection
# ---------------------------------------------------------------------------
def _reasoning_tokens_from_usage(usage: object | None) -> int | None:
    if usage is None:
        return None
    ctd = getattr(usage, "completion_tokens_details", None)
    if ctd is None:
        return None
    return getattr(ctd, "reasoning_tokens", None)


def _log_chat_completion_diagnostics(
    label: str,
    response: object,
    choice: object,
    raw_content: str | None,
    stripped: str,
) -> None:
    """Log response metadata to stderr so empty outputs can be diagnosed (usage, finish_reason, etc.)."""
    usage = getattr(response, "usage", None)
    usage_s = ""
    if usage is not None:
        pt = getattr(usage, "prompt_tokens", None)
        ct = getattr(usage, "completion_tokens", None)
        tt = getattr(usage, "total_tokens", None)
        usage_s = f" prompt_tokens={pt} completion_tokens={ct} total_tokens={tt}"
        ctd = getattr(usage, "completion_tokens_details", None)
        if ctd is not None:
            # e.g. reasoning models: many tokens in details but message.content empty
            usage_s += f" completion_tokens_details={ctd!r}"
    rid = getattr(response, "id", None)
    model = getattr(response, "model", None)
    finish = getattr(choice, "finish_reason", None)
    raw_kind = "None" if raw_content is None else f"str(len={len(raw_content)})"
    print(
        f"[select_tests] {label}: response_id={rid!r} model={model!r} finish_reason={finish!r}{usage_s}",
        file=sys.stderr,
    )
    print(
        f"[select_tests] {label}: message.content {raw_kind} stripped_len={len(stripped)}",
        file=sys.stderr,
    )
    if not stripped:
        refusal = getattr(choice.message, "refusal", None)
        tool_calls = getattr(choice.message, "tool_calls", None)
        print(
            f"[select_tests] {label}: refusal={refusal!r} tool_calls={tool_calls!r}",
            file=sys.stderr,
        )
        if finish == "length":
            print(
                f"[select_tests] {label}: Hint: finish_reason=length — output may be truncated; "
                "raise AZURE_OPENAI_SELECTION_MAX_COMPLETION_TOKENS or STAGE1/STAGE2 token env vars.",
                file=sys.stderr,
            )
        elif finish == "stop" and raw_content is None:
            print(
                f"[select_tests] {label}: Hint: content is None with finish_reason=stop — deployment may "
                "omit text (e.g. reasoning-only field) or hit a limit; retry, change deployment, or reduce prompt size.",
                file=sys.stderr,
            )
        elif finish == "stop" and (raw_content is not None) and not stripped:
            if raw_content == "":
                print(
                    f"[select_tests] {label}: Hint: empty string in message.content — model used "
                    f"{getattr(usage, 'completion_tokens', None)!r} completion_tokens but no visible text; "
                    "common with reasoning models (see completion_tokens_details), oversized prompts "
                    "(raise STAGE2_MAX_TOTAL_SNIPPET_CHARS or narrow Stage 1), or deployment quirks.",
                    file=sys.stderr,
                )
                rt = _reasoning_tokens_from_usage(usage)
                ct = getattr(usage, "completion_tokens", None)
                if (
                    rt is not None
                    and ct is not None
                    and isinstance(ct, int)
                    and ct > 0
                    and rt >= ct - 50
                ):
                    print(
                        f"[select_tests] {label}: Hint: reasoning_tokens ({rt}) used almost all "
                        f"completion_tokens ({ct}) — raise AZURE_OPENAI_STAGE2_MAX_COMPLETION_TOKENS "
                        "(e.g. 32768) so the model can emit text after reasoning, or use a "
                        "non-reasoning deployment for Stage 2. Optional: STAGE2_FALLBACK_STAGE1=1 uses "
                        "Stage-1 candidates when Stage 2 is empty.",
                        file=sys.stderr,
                    )
            else:
                print(
                    f"[select_tests] {label}: Hint: whitespace-only content — model returned no visible paths.",
                    file=sys.stderr,
                )
        else:
            print(
                f"[select_tests] {label}: Hint: empty paths after strip — model may intend 'no tests' "
                "(see system prompt) or output was unusable.",
                file=sys.stderr,
            )
    if os.environ.get("SELECT_TESTS_VERBOSE_AZURE", "").strip() in ("1", "true", "yes"):
        if raw_content is not None and not stripped:
            preview = repr(raw_content)
            if len(preview) > 500:
                preview = preview[:500] + "..."
            print(f"[select_tests] {label}: raw content preview: {preview}", file=sys.stderr)


def call_azure_openai_for_selection(
    system_message: str,
    user_message: str,
    *,
    max_completion_tokens: int | None = None,
    log_label: str = "Azure",
) -> str:
    """
    Call Azure OpenAI chat completions with the given messages.
    Returns the assistant reply text. Exits with code 1 on missing env / package.
    Raises RuntimeError on API / transport failure (caller may fall back to all tests).
    """
    try:
        from openai import AzureOpenAI
    except ImportError:
        print("Error: openai package required. Run: pip install -r requirements.txt", file=sys.stderr)
        sys.exit(1)

    api_key = os.environ.get("AZURE_OPENAI_API_KEY")
    endpoint = os.environ.get("AZURE_OPENAI_ENDPOINT")
    deployment = os.environ.get("AZURE_OPENAI_DEPLOYMENT")

    if not api_key or not endpoint or not deployment:
        print(
            "Error: Set AZURE_OPENAI_API_KEY, AZURE_OPENAI_ENDPOINT, and AZURE_OPENAI_DEPLOYMENT.",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        timeout_env = os.environ.get("AZURE_OPENAI_TIMEOUT_SECONDS", "").strip()
        timeout_sec: float | None = float(timeout_env) if timeout_env else None

        _client_kw = {
            "api_key": api_key,
            "azure_endpoint": endpoint.rstrip("/"),
            "api_version": os.environ.get("AZURE_OPENAI_API_VERSION", "2024-02-15-preview"),
        }
        if timeout_sec is not None:
            _client_kw["timeout"] = timeout_sec
        client = AzureOpenAI(**_client_kw)
        # Large prompts (many specs) + some models (e.g. reasoning) can hit the limit at 1024
        # and return empty content with finish_reason=length.
        max_completion = max_completion_tokens if max_completion_tokens is not None else _default_max_completion_tokens()
        log_step(
            f"{log_label} API request starting",
            f"system={len(system_message)} chars, user={len(user_message)} chars, "
            f"max_completion_tokens={max_completion}, timeout_sec={timeout_sec!r}, deployment={deployment!r}",
        )
        t0 = time.monotonic()
        response = client.chat.completions.create(
            model=deployment,
            messages=[
                {"role": "system", "content": system_message},
                {"role": "user", "content": user_message},
            ],
            max_completion_tokens=max_completion,
        )
        elapsed = time.monotonic() - t0
        choice = response.choices[0]
        raw = choice.message.content
        content = (raw or "").strip()
        log_step(
            f"{log_label} API request finished OK",
            f"elapsed={elapsed:.2f}s, stripped_content_len={len(content)}",
        )
        _log_chat_completion_diagnostics(log_label, response, choice, raw, content)
        return content
    except Exception as e:
        _log_azure_api_exception(log_label, e)
        raise RuntimeError(f"Azure OpenAI API call failed ({log_label}): {e}") from e


# ---------------------------------------------------------------------------
# Checkpoint 6: Parse and validate model response
# ---------------------------------------------------------------------------
def parse_and_validate_response(model_response: str, allowed_paths: set[str]) -> list[str]:
    """
    Parse the model's reply into a list of test paths. Validates against allowed_paths.
    Returns [] if empty or no valid paths (no tests to run).
    Preserves first-seen order; drops duplicates.
    API errors are handled in main() with a separate fallback to all tests.
    """
    lines = [line.strip() for line in model_response.splitlines() if line.strip()]
    paths: list[str] = []
    seen: set[str] = set()
    for line in lines:
        # If model returned "path — summary" or "path: summary", take path only
        for sep in (" — ", ": "):
            if sep in line:
                line = line.split(sep)[0].strip()
                break
        # Strip common markdown bullet prefixes
        if line.startswith(("- ", "* ", "• ")):
            line = line[2:].strip()
        # Normalize path separators to forward slash
        path = line.replace("\\", "/")
        if path in allowed_paths and path not in seen:
            seen.add(path)
            paths.append(path)
    return paths


def _spec_basename_lower(path: str) -> str:
    """Filename only, lowercased, .spec.js stripped."""
    name = path.replace("\\", "/").split("/")[-1]
    return name.replace(".spec.js", "").lower()


def _diff_words_for_merge(full_diff: str | None) -> set[str]:
    """Words of length >= 4 from the diff (lowercase), for alignment checks."""
    if not full_diff or not full_diff.strip():
        return set()
    return {m.lower() for m in re.findall(r"[A-Za-z]{4,}", full_diff)}


def _should_merge_stage1_candidate(
    candidate_path: str,
    diff_words: set[str],
    changed_blob: str,
) -> bool:
    """
    True if this Stage-1 candidate should be unioned with Stage 2 output because it is
    strongly aligned with the diff text and changed file path (reduces dropped specific specs).
    Conservative: avoids merging unrelated toolbar specs unless rules match.
    """
    cl = candidate_path.lower()
    base = _spec_basename_lower(candidate_path)
    diff_hits = sum(1 for w in diff_words if len(w) >= 4 and w in cl)
    if diff_hits < 2:
        return False

    changed_blob = changed_blob.lower()

    # Change under wheel / tools.js: prefer specs whose basename names a tool or wheel
    if "wheel" in changed_blob or "tools.js" in changed_blob:
        if "tool" in base or "wheel" in base:
            return True

    # Window/level tool files: basename should contain window, level, and tool (e.g. windowLevelTool.spec.js)
    if "window" in base and "level" in base and "tool" in base:
        return True

    return False


def _should_merge_datagrid_worklist_selection(
    changed_files: list[str],
    full_diff: str | None,
    candidate_path: str,
) -> bool:
    """
    Merge WorklistSelection/worklistSelection.spec.js when DataGrid changes include data-cy / worklist table hooks.
    Reduces confusion with WorklistSelector when Stage 2 picks the wrong spec.
    """
    if not full_diff:
        return False
    if not any("datagrid.jsx" in f.replace("\\", "/").lower() for f in changed_files):
        return False
    dl = full_diff.lower()
    if not ("data-cy" in dl or "worklist-study" in dl or "study-status" in dl):
        return False
    cap = candidate_path.replace("\\", "/").lower()
    return cap == "worklistselection/worklistselection.spec.js" or cap.endswith(
        "/worklistselection.spec.js"
    )


def _should_merge_org_user_login_email(
    changed_files: list[str],
    full_diff: str | None,
    candidate_path: str,
) -> bool:
    """
    Merge User/disableLoginEmail.spec.js when OrganizationUser.jsx changes mention login/email copy.
    Helps multi-file diffs where Stage 2 keeps only worklist-related specs.
    """
    if not full_diff:
        return False
    if not any("organizationuser.jsx" in f.replace("\\", "/").lower() for f in changed_files):
        return False
    dl = full_diff.lower()
    if "login" not in dl and "email" not in dl:
        return False
    cap = candidate_path.replace("\\", "/").lower()
    return cap.endswith("/disableloginemail.spec.js")


def merge_stage2_with_stage1_path_alignment(
    stage2_paths: list[str],
    stage1_candidates: list[str],
    changed_files: list[str],
    full_diff: str | None,
    *,
    allowed_candidates: set[str],
) -> tuple[list[str], list[str]]:
    """
    Union Stage 2 paths with Stage-1 candidates that pass _should_merge_stage1_candidate.
    Only considers candidates in allowed_candidates (e.g. specs we could load for Stage 2).
    Returns (merged_paths, boosted_paths_only) where boosted are those not in stage2_paths.
    Preserves order: Stage 2 order first, then boosted in stage1 order.
    """
    diff_words = _diff_words_for_merge(full_diff)
    changed_blob = " ".join(changed_files)
    s2 = set(stage2_paths)
    out = list(stage2_paths)
    boosted: list[str] = []
    for c in stage1_candidates:
        if c not in allowed_candidates:
            continue
        if c in s2:
            continue
        if _should_merge_stage1_candidate(c, diff_words, changed_blob):
            out.append(c)
            s2.add(c)
            boosted.append(c)
        elif _should_merge_datagrid_worklist_selection(changed_files, full_diff, c):
            out.append(c)
            s2.add(c)
            boosted.append(c)
        elif _should_merge_org_user_login_email(changed_files, full_diff, c):
            out.append(c)
            s2.add(c)
            boosted.append(c)
    return out, boosted


def get_changed_files_and_diff(args) -> tuple[list[str], str | None]:
    """
    Return (changed_file_paths, full_diff_text).
    full_diff_text is None when using --diff-file only for name-only style parsing.
    """
    if args.diff_file:
        diff_path = Path(args.diff_file)
        if not diff_path.is_absolute():
            diff_path = Path.cwd() / diff_path
        if not diff_path.exists():
            raise FileNotFoundError(f"Diff file not found: {diff_path}")
        full_diff = diff_path.read_text(encoding="utf-8", errors="replace")
        changed = parse_diff_git_paths(full_diff)
        return changed, full_diff

    repo_path = resolve_repo_path(args.repo)
    if not repo_path.is_dir():
        raise NotADirectoryError(f"Repo path is not a directory: {repo_path}")

    # Changed file names (one per line)
    name_only = run_git(repo_path, "diff", args.base, args.head, "--name-only")
    changed = [line.strip() for line in name_only.splitlines() if line.strip()]

    # Full diff for prompt (optional)
    full_diff = run_git(repo_path, "diff", args.base, args.head)
    return changed, full_diff if full_diff.strip() else None


def write_final_selected_paths(path: Path, paths: list[str]) -> None:
    """Write last_model_response.txt: one spec path per line, or (none) if empty."""
    if not paths:
        path.write_text("(none)\n", encoding="utf-8")
    else:
        path.write_text("\n".join(paths) + "\n", encoding="utf-8")


def print_playwright_command(selected_paths: list[str]) -> None:
    """Print suggested npx line from Worklist-2."""
    if selected_paths:
        cmd_paths = " ".join(f"playwright/{p}" for p in selected_paths)
        print(f"\nRun from OmegaAI-Mono/Worklist-2:\n  npx playwright test {cmd_paths}")
    else:
        print("\nRun from OmegaAI-Mono/Worklist-2:\n  (no tests selected — no npx command)")


def run_two_stage_flow(
    args: argparse.Namespace,
    repo_path: Path,
    playwright_paths: list[str],
    allowed_set: set[str],
    changed_files: list[str],
    full_diff: str | None,
) -> None:
    """
    Stage 1: summaries → wide-net candidate paths.
    Stage 2: truncated spec bodies for candidates → final paths (precision-first unless --stage2-recall).
    last_model_response.txt = final selected paths (one per line); raw Stage 2 → last_model_raw_response.txt.
    """
    scripts_dir = Path(__file__).resolve().parent
    stage1_artifact = scripts_dir / "last_stage1_candidates.txt"
    out_file = scripts_dir / "last_model_response.txt"
    raw_response_file = scripts_dir / "last_model_raw_response.txt"
    merged_paths_file = scripts_dir / "last_stage2_merged_paths.txt"

    log_step("two-stage flow start", f"changed_files={len(changed_files)}, dry_run={args.dry_run}")

    available_tests = get_test_summaries(repo_path)
    print(f"\nTwo-stage: Stage 1 — path + summary for {len(available_tests)} spec(s).")

    s1_sys, s1_user = build_stage1_candidate_prompt(changed_files, full_diff, available_tests)
    log_step("Stage 1 prompt ready", f"system={len(s1_sys)} user={len(s1_user)} chars")
    print(f"\nStage 1 prompt: system={len(s1_sys)} chars, user={len(s1_user)} chars")
    print("Stage 1 user preview (first 400 chars):")
    print(s1_user[:400] + ("..." if len(s1_user) > 400 else ""))

    selected_paths: list[str] = []

    if args.dry_run:
        print("\n(dry-run: skipping Stage 1 & 2 Azure calls.)")
        print(
            "Stage 2 builds its prompt after Stage 1 returns candidate paths "
            "(truncated spec snippets per candidate).",
            file=sys.stderr,
        )
        print("\nSelected tests:\n  (dry-run — none)")
        print_playwright_command([])
        return

    # --- Stage 1 ---
    try:
        log_step("Stage 1", "calling Azure OpenAI (wide-net candidates)")
        r1 = call_azure_openai_for_selection(
            s1_sys,
            s1_user,
            max_completion_tokens=_stage1_max_completion_tokens(),
            log_label="Stage 1",
        )
    except RuntimeError as e:
        print(f"Warning: {e}", file=sys.stderr)
        print(
            "Falling back to all tests (safe default when the API call fails).",
            file=sys.stderr,
        )
        stage1_artifact.write_text(f"(Stage 1 API error — fallback to all tests)\n{e}", encoding="utf-8")
        raw_response_file.write_text(f"(Stage 1 API error — no Stage 2)\n{e}", encoding="utf-8")
        selected_paths = list(playwright_paths)
        write_final_selected_paths(out_file, selected_paths)
        print(f"\nFinal paths written to: {out_file}", file=sys.stderr)
        print(f"\nStage 1 raw response written to: {stage1_artifact}", file=sys.stderr)
        print("\nStage 1 model response: (not available — API error)")
        print("\nSelected tests:")
        for p in selected_paths:
            print(f"  {p}")
        print_playwright_command(selected_paths)
        return

    stage1_artifact.write_text(r1 or "(empty)", encoding="utf-8")
    print(f"\nStage 1 raw response written to: {stage1_artifact}", file=sys.stderr)
    print(f"\nStage 1 model response ({len(r1 or '')} chars):")
    print(r1 or "(empty)")

    candidates = parse_and_validate_response(r1 or "", allowed_set)
    log_step(
        "Stage 1 parse + validate",
        f"{len(candidates)} path(s) matched allowlist (empty model text or no valid lines → 0)",
    )
    if not candidates:
        raw_response_file.write_text(
            f"(Stage 1 returned no valid candidate paths — skipping Stage 2)\n{r1 or '(empty)'}",
            encoding="utf-8",
        )
        write_final_selected_paths(out_file, [])
        print(f"\nFinal paths written to: {out_file}", file=sys.stderr)
        print(f"Raw / status written to: {raw_response_file}", file=sys.stderr)
        print(
            "\nNote: No valid paths after Stage 1 — no tests selected.",
            file=sys.stderr,
        )
        print("\nSelected tests:\n  (none)")
        print_playwright_command([])
        return

    if args.stage2_recall:
        stage2_mode = "recall"
    elif getattr(args, "stage2_balanced", False):
        stage2_mode = "balanced"
    else:
        stage2_mode = "precision"
    _s2_mode_label = {
        "precision": "precision-first (default)",
        "balanced": "balanced (--stage2-balanced: slightly wider than precision)",
        "recall": "recall-first (--stage2-recall)",
    }[stage2_mode]
    print(f"\nStage 2 prompt mode: {_s2_mode_label}", file=sys.stderr)

    s2_cap = stage2_per_spec_max_chars(len(candidates))
    budget = _stage2_total_snippet_budget_chars()
    print(
        f"\nStage 2 snippet budget: total={budget} chars across {len(candidates)} candidate(s) "
        f"→ max {s2_cap} chars/spec (STAGE2_SPEC_MAX_CHARS={STAGE2_SPEC_MAX_CHARS} upper bound).",
        file=sys.stderr,
    )
    if s2_cap < STAGE2_SPEC_MAX_CHARS:
        print(
            "Stage 2: per-spec snippets reduced so the prompt stays smaller — avoids empty model "
            "replies on very large Stage-2 prompts. Override with STAGE2_MAX_TOTAL_SNIPPET_CHARS in .env.",
            file=sys.stderr,
        )

    log_step("Stage 2 load spec snippets", f"reading {len(candidates)} candidate file(s) from repo")
    snippets = get_truncated_spec_snippets(repo_path, candidates, max_chars=s2_cap)
    allowed_stage2 = {p for p, _ in snippets}
    log_step("Stage 2 snippets loaded", f"{len(snippets)} snippet(s), allowed_stage2={len(allowed_stage2)}")
    if not snippets:
        raw_response_file.write_text(
            "(Stage 2 skipped: no readable spec files for Stage-1 candidates.)",
            encoding="utf-8",
        )
        write_final_selected_paths(out_file, [])
        print(f"\nFinal paths written to: {out_file}", file=sys.stderr)
        print(
            "\nWarning: Could not read any candidate spec files for Stage 2.",
            file=sys.stderr,
        )
        print("\nSelected tests:\n  (none)")
        print_playwright_command([])
        return

    s2_sys, s2_user = build_stage2_final_prompt(
        changed_files, full_diff, snippets, stage2_mode=stage2_mode
    )
    log_step("Stage 2 prompt ready", f"system={len(s2_sys)} user={len(s2_user)} chars")
    if len(s2_user) > 150_000:
        print(
            f"\nWarning: Stage 2 user message is very large ({len(s2_user)} chars). "
            "If the model returns empty content, lower STAGE2_MAX_TOTAL_SNIPPET_CHARS or reduce Stage 1 recall.",
            file=sys.stderr,
        )
    print(f"\nStage 2 prompt: system={len(s2_sys)} chars, user={len(s2_user)} chars")
    print("Stage 2 user preview (first 400 chars):")
    print(s2_user[:400] + ("..." if len(s2_user) > 400 else ""))

    try:
        log_step("Stage 2", "calling Azure OpenAI (final path list from snippets)")
        r2 = call_azure_openai_for_selection(
            s2_sys,
            s2_user,
            max_completion_tokens=_stage2_max_completion_tokens(),
            log_label="Stage 2",
        )
    except RuntimeError as e:
        print(f"Warning: {e}", file=sys.stderr)
        print(
            "Falling back to all tests (safe default when the API call fails).",
            file=sys.stderr,
        )
        raw_response_file.write_text(f"(Stage 2 API error — fallback to all tests)\n{e}", encoding="utf-8")
        selected_paths = list(playwright_paths)
        write_final_selected_paths(out_file, selected_paths)
        print(f"\nFinal paths written to: {out_file}", file=sys.stderr)
        print("\nStage 2 model response: (not available — API error)")
        print("\nSelected tests:")
        for p in selected_paths:
            print(f"  {p}")
        print_playwright_command(selected_paths)
        return

    raw_response_file.write_text(r2 or "(empty)", encoding="utf-8")
    print(f"\nRaw Stage 2 response written to: {raw_response_file}", file=sys.stderr)
    print(f"\nStage 2 model response ({len(r2 or '')} chars):")
    print(r2 or "(empty)")

    selected_paths = parse_and_validate_response(r2 or "", allowed_stage2)
    log_step(
        "Stage 2 parse + validate",
        f"{len(selected_paths)} path(s) after parse (empty Stage 2 text → 0)",
    )

    boosted: list[str] = []
    if stage2_mode != "recall":
        log_step("Stage 2 merge with Stage 1", "path-alignment heuristics")
        selected_paths, boosted = merge_stage2_with_stage1_path_alignment(
            selected_paths,
            candidates,
            changed_files,
            full_diff,
            allowed_candidates=allowed_stage2,
        )
        log_step("Stage 2 merge done", f"final count={len(selected_paths)}, boosted={len(boosted)}")
        if boosted:
            print(
                f"\nMerged {len(boosted)} Stage-1 path(s) (diff/path alignment): {', '.join(boosted)}",
                file=sys.stderr,
            )
            merged_paths_file.write_text("\n".join(boosted) + "\n", encoding="utf-8")
            print(f"Merged paths written to: {merged_paths_file}", file=sys.stderr)
        else:
            merged_paths_file.write_text("(none)\n", encoding="utf-8")
    else:
        merged_paths_file.write_text("(merge skipped: Stage 2 recall mode)\n", encoding="utf-8")

    if (
        not selected_paths
        and not (r2 or "").strip()
        and candidates
        and os.environ.get("STAGE2_FALLBACK_STAGE1", "").strip().lower() in ("1", "true", "yes")
    ):
        selected_paths = [p for p in candidates if p in allowed_stage2]
        log_step(
            "STAGE2_FALLBACK_STAGE1",
            f"using {len(selected_paths)} Stage-1 path(s) because Stage 2 output was empty",
        )
        print(
            f"\nStage 2 empty — STAGE2_FALLBACK_STAGE1: using {len(selected_paths)} path(s) from Stage 1 "
            "(set STAGE2_FALLBACK_STAGE1=0 to disable).",
            file=sys.stderr,
        )

    write_final_selected_paths(out_file, selected_paths)
    print(f"\nFinal paths written to: {out_file}", file=sys.stderr)

    if not selected_paths:
        if not (r2 or "").strip():
            print(
                "\nNote: Stage 2 returned empty content — no tests selected.",
                file=sys.stderr,
            )
        else:
            print(
                "\nNote: Stage 2 reply had no valid test paths — no tests selected.",
                file=sys.stderr,
            )

    print("\nSelected tests:")
    if not selected_paths:
        print("  (none)")
    else:
        for p in selected_paths:
            print(f"  {p}")
    log_step("two-stage flow complete", f"final selected_paths={len(selected_paths)}")
    print_playwright_command(selected_paths)


def main():
    parser = argparse.ArgumentParser(description="Select E2E tests to run based on code diff via Azure OpenAI.")
    parser.add_argument("--repo", default="../OmegaAI-Mono", help="Path to OmegaAI-Mono repo root")
    parser.add_argument("--base", default="master", help="Base ref for git diff")
    parser.add_argument("--head", default="HEAD", help="Head ref for git diff")
    parser.add_argument("--diff-file", help="Path to pre-saved diff file (optional, instead of base/head)")
    parser.add_argument("--approach", choices=("summaries", "full"), default="summaries",
                        help="summaries = path + one-line summary per test; full = full spec file content")
    parser.add_argument("--dry-run", action="store_true",
                        help="build prompt but do not call Azure OpenAI (no API key needed)")
    parser.add_argument(
        "--two-stage",
        action="store_true",
        help=(
            "Two-step selection: Stage 1 = wide-net candidates from summaries; Stage 2 = final paths "
            "using truncated spec bodies (precision-first by default). Single-shot (default) uses --approach."
        ),
    )
    parser.add_argument(
        "--stage2-recall",
        action="store_true",
        help=(
            "With --two-stage only: Stage 2 recall-first (keep every plausible candidate). "
            "Mutually exclusive with --stage2-balanced."
        ),
    )
    parser.add_argument(
        "--stage2-balanced",
        action="store_true",
        help=(
            "With --two-stage only: Stage 2 balanced mode — slightly more tests than precision-default "
            "(e.g. 2–5 paths when several distinct flows apply). Mutually exclusive with --stage2-recall."
        ),
    )
    args = parser.parse_args()

    if args.stage2_recall and not args.two_stage:
        print("Error: --stage2-recall requires --two-stage.", file=sys.stderr)
        sys.exit(1)
    if args.stage2_balanced and not args.two_stage:
        print("Error: --stage2-balanced requires --two-stage.", file=sys.stderr)
        sys.exit(1)
    if args.stage2_recall and args.stage2_balanced:
        print("Error: use only one of --stage2-recall or --stage2-balanced.", file=sys.stderr)
        sys.exit(1)

    # Avoid UnicodeEncodeError on Windows (cp1252) when printing summaries with special chars
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8", errors="replace")
            except Exception:
                pass

    repo_path = resolve_repo_path(args.repo)
    if not repo_path.is_dir():
        print(f"Error: repo path is not a directory: {repo_path}", file=sys.stderr)
        sys.exit(1)

    playwright_paths = discover_playwright_spec_paths(repo_path)
    if not playwright_paths:
        print(
            f"Error: no *.spec.js files under {playwright_dir(repo_path)}",
            file=sys.stderr,
        )
        sys.exit(1)
    allowed_set = set(playwright_paths)

    try:
        changed_files, full_diff = get_changed_files_and_diff(args)
    except (RuntimeError, FileNotFoundError, NotADirectoryError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    log_step(
        "git diff loaded",
        f"{len(changed_files)} file(s), diff_len={len(full_diff) if full_diff else 0}",
    )

    # Checkpoint 2: output for verification
    print(f"Discovered {len(playwright_paths)} Playwright spec(s) under Worklist-2/playwright.")
    print("Changed files:")
    for p in changed_files:
        print(f"  {p}")
    if full_diff is not None:
        print(f"\nFull diff length: {len(full_diff)} chars")
    else:
        print("\nFull diff: (none captured)")

    if args.two_stage:
        if args.approach != "summaries":
            print(
                "Note: --two-stage uses summaries for Stage 1 and spec snippets for Stage 2; "
                "--approach is ignored.",
                file=sys.stderr,
            )
        run_two_stage_flow(args, repo_path, playwright_paths, allowed_set, changed_files, full_diff)
        return

    # Checkpoint 3: available tests (summaries or full content per --approach)
    try:
        available_tests = get_available_tests(repo_path, args.approach)
    except (ValueError, NotADirectoryError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    log_step("available tests loaded", f"approach={args.approach}, count={len(available_tests)}")
    print(f"\nAvailable tests (approach={args.approach}):")
    for path, text in available_tests:
        preview = text[:80] + "..." if len(text) > 80 else text
        print(f"  {path}: {preview!r}")

    # Checkpoint 4: build prompt for AI
    system_msg, user_msg = build_prompt(changed_files, full_diff, available_tests)
    log_step("single-shot prompt built", f"system={len(system_msg)} user={len(user_msg)} chars")
    print(f"\nPrompt built: system={len(system_msg)} chars, user={len(user_msg)} chars")
    print("User message preview (first 400 chars):")
    print(user_msg[:400] + ("..." if len(user_msg) > 400 else ""))

    # Checkpoint 5: call Azure OpenAI for test selection
    if args.dry_run:
        log_step("single-shot", "dry-run — skipping Azure OpenAI")
        print("\n(dry-run: skipping Azure OpenAI call)")
    else:
        _scripts_dir = Path(__file__).resolve().parent
        _out_file = _scripts_dir / "last_model_response.txt"
        _raw_file = _scripts_dir / "last_model_raw_response.txt"
        selected_paths: list[str] = []
        try:
            log_step("single-shot", "calling Azure OpenAI")
            model_response = call_azure_openai_for_selection(
                system_msg,
                user_msg,
                max_completion_tokens=_default_max_completion_tokens(),
                log_label="single-shot",
            )
        except RuntimeError as e:
            # API / transport failure: safe default is run all tests
            print(f"Warning: {e}", file=sys.stderr)
            print(
                "Falling back to all tests (safe default when the API call fails).",
                file=sys.stderr,
            )
            _raw_file.write_text(f"(API error — fallback to all tests)\n{e}", encoding="utf-8")
            selected_paths = list(playwright_paths)
            write_final_selected_paths(_out_file, selected_paths)
            print(f"\nRaw assistant text written to: {_raw_file}", file=sys.stderr)
            print(f"\nFinal paths written to: {_out_file}", file=sys.stderr)
            print("\nModel response: (not available — API error)")
        else:
            print(f"\nModel response ({len(model_response)} chars):")
            print(model_response or "(empty)")

            _raw_file.write_text(model_response or "(empty)", encoding="utf-8")
            print(f"\nRaw assistant text written to: {_raw_file}", file=sys.stderr)

            # Successful API: empty or unparseable reply → no tests (not all tests)
            selected_paths = parse_and_validate_response(model_response, allowed_set)
            log_step(
                "single-shot parse + validate",
                f"{len(selected_paths)} path(s) (empty reply or unknown paths → 0)",
            )
            write_final_selected_paths(_out_file, selected_paths)
            print(f"\nFinal paths written to: {_out_file}", file=sys.stderr)
            if not selected_paths:
                if not (model_response or "").strip():
                    print(
                        "\nNote: Model returned empty content — no tests selected.",
                        file=sys.stderr,
                    )
                else:
                    print(
                        "\nNote: Model reply had no valid test paths (e.g. none required) — no tests selected.",
                        file=sys.stderr,
                    )

        log_step("single-shot flow complete", f"final selected_paths={len(selected_paths)}")
        print("\nSelected tests:")
        if not selected_paths:
            print("  (none)")
        else:
            for p in selected_paths:
                print(f"  {p}")
        print_playwright_command(selected_paths)


if __name__ == "__main__":
    main()
